from sqlalchemy import Column, DECIMAL, Date, MetaData, String, Table, text
from sqlalchemy.dialects.mysql import TIMESTAMP

metadata = MetaData()

t_RS_RETURNSHEET_GRID = Table(
    'RS_RETURNSHEET_GRID', metadata,
    Column('Z_RECORD_ID', String(55)),
    Column('Z_TAXPAYER_AGGREGATE_IDENTIFIER', String(55)),
    Column('Z_AGGREGATE_IDENTIFIER', String(55)),
    Column('Z_AGGREGATE_VERSION', DECIMAL(19, 0)),
    Column('Z_TAX_TYPE_CODE', String(255)),
    Column('Z_RETURN_SHEET_TYPE_CODE', String(255)),
    Column('Z_TAX_PERIOD_CODE', String(255)),
    Column('Z_RETURN_SHEET_STATUS_CODE', String(255)),
    Column('Z_RETURN_SHEET_VERSION_CODE', String(255)),
    Column('Z_EXPECTED_RETURN_DATE', Date),
    Column('Z_RETURN_DATE', Date),
    Column('Z_ENTERED_DATE', Date),
    Column('Z_ASSESSMENT_DATE', Date),
    Column('Z_RETURN_SHEET_MODEL', String(255)),
    Column('Z_TAX_OBJECT_DECIMAL', String(50)),
    Column('Z_TAX_REGION_CODE', String(255)),
    Column('Z_TAX_OFFICE_CODE', String(255)),
    Column('Z_LETTER_APPENDIX', String(255)),
    Column('Z_SUBMIT_TIMESTAMP', DECIMAL(19, 0)),
    Column('Z_REJECTION_REASON', String(255)),
    Column('Z_TOTAL_DECLARED_AMOUNT', DECIMAL(38, 8)),
    Column('Z_DATE_NOTICE_OF_LATE_FILLING', String(255)),
    Column('Z_BOOKKEEPING_PERIOD', String(10)),
    Column('Z_PROCESS_REQUEST_STATUS', String(256)),
    Column('Z_BPS_NO', String(100)),
    Column('Z_CHANNEL_CODE', String(100)),
    Column('Z_DATE_OF_RECEIPT', Date),
    Column('Z_PROOF_OF_RECEIPT', String(100)),
    Column('Z_IS_ARCHIVED', DECIMAL(1, 0), server_default=text('0')),
    Column('Z_LAST_UPDATED_DATE', TIMESTAMP(fsp=6), nullable=False, server_default=text('current_timestamp(6) ON UPDATE current_timestamp(6)')),
    Column('Z_REJECTION_DECIMAL', String(100)),
    Column('Z_IS_MIGRATED', DECIMAL(1, 0), server_default=text('0')),
    Column('Z_IS_MIGRATED_AND_UPDATED', DECIMAL(1, 0), server_default=text('0')),
    Column('Z_CREATION_DATE', TIMESTAMP(fsp=6), nullable=False, server_default=text('current_timestamp(6)')),
    Column('Z_PREFILL_STATUS', String(50)),
    Column('Z_PREFILL_LAST_UPDATED', TIMESTAMP(fsp=6), nullable=False, server_default=text("'0000-00-00 00:00:00.000000'")),
    Column('Z_PREFILL_START', TIMESTAMP(fsp=6), nullable=False, server_default=text("'0000-00-00 00:00:00.000000'")),
    Column('Z_PREFILL_END', TIMESTAMP(fsp=6), nullable=False, server_default=text("'0000-00-00 00:00:00.000000'")),
    Column('Z_IS_TRANSACTION_WITH_RELATED', DECIMAL(1, 0)),
    Column('Z_DOCUMENT_FORM_DECIMAL', String(255)),
    Column('Z_DOCUMENT_FORM_AGGREGATE_IDENTIFIER', String(16)),
    Column('Z_DOCUMENT_RECEIPT_DECIMAL', String(255)),
    Column('Z_DOCUMENT_RECEIPT_AGGREGATE_IDENTIFIER', String(16)),
    Column('Z_RETURN_SHEET_DECIMAL', String(100)),
    Column('Z_SUBMIT_IN_PROGRESS_STATUS', DECIMAL(1, 0), server_default=text('0'))
)
